### ISSUE TITLE
Sources from .bib file only show if at least one source is in .json file

### ISSUE THREAD

**Issue by gertminov** [aeudes/slidev-addon-citations#4]
Hi, first off thank you very much for creating this addon. Since it works it is fantastic.
I've encountered a small bug.
I have my sources in a `.bib` file in `/public/biblio/sources.bib` which i have referenced in  the frontmatter of the slides.
When i try to cite my source it shows up as `(#RefErr)`. But as soon as i add the `ig2022.json` (from your example) in the same folder in reference it in the frontmatter, my original sources load correctly. When i delete all entries from the json array, it breaks again.

I have linked repo with a minimal example [here](https://github.com/gertminov/slidev-bib-addon-bug)

**Comment by aeudes** [comment]
Thanks for reporting with this very helpful minimal example !
I fixed the bug with #5, the new upstream version should work as expected.
